<?php
$cities=[
["city"=>"Achhnera","state"=>"Uttar Pradesh","id"=>"1037"],
["city"=>"Adalaj","state"=>"Gujarat","id"=>"209"],
["city"=>"Adilabad","state"=>"Telangana","id"=>"990"],
["city"=>"Adityapur","state"=>"Jharkhand","id"=>"333"],
["city"=>"Adoni","state"=>"Andhra Pradesh","id"=>"2"],
["city"=>"Adoor","state"=>"Kerala","id"=>"440"],
["city"=>"Adra","state"=>"West Bengal","id"=>"1173"],
["city"=>"Adyar","state"=>"Karnataka","id"=>"360"],
["city"=>"Afzalpur","state"=>"Karnataka","id"=>"361"],
["city"=>"Agartala*","state"=>"Tripura","id"=>"1030"],
["city"=>"Agra","state"=>"Uttar Pradesh","id"=>"1038"],
["city"=>"Ahmedabad","state"=>"Gujarat","id"=>"210"],
["city"=>"Ahmednagar","state"=>"Maharashtra","id"=>"574"],
["city"=>"Aizawl","state"=>"Mizoram","id"=>"702"],
["city"=>"Ajmer","state"=>"Rajasthan","id"=>"803"],
["city"=>"Akola","state"=>"Maharashtra","id"=>"575"],
["city"=>"Akot","state"=>"Maharashtra","id"=>"576"],
["city"=>"Alappuzha","state"=>"Kerala","id"=>"441"],
["city"=>"Aligarh","state"=>"Uttar Pradesh","id"=>"1039"],
["city"=>"Alipurduar","state"=>"West Bengal","id"=>"1174"],
["city"=>"Alirajpur","state"=>"Madhya Pradesh","id"=>"491"],
["city"=>"Allahabad","state"=>"Uttar Pradesh","id"=>"1040"],
["city"=>"Alwar","state"=>"Rajasthan","id"=>"804"],
["city"=>"Amalapuram","state"=>"Andhra Pradesh","id"=>"3"],
["city"=>"Amalner","state"=>"Maharashtra","id"=>"577"],
["city"=>"Ambejogai","state"=>"Maharashtra","id"=>"578"],
["city"=>"Ambikapur","state"=>"Chhattisgarh","id"=>"183"],
["city"=>"Amravati","state"=>"Maharashtra","id"=>"579"],
["city"=>"Amreli","state"=>"Gujarat","id"=>"211"],
["city"=>"Amritsar","state"=>"Punjab","id"=>"749"],
["city"=>"Amroha","state"=>"Uttar Pradesh","id"=>"1041"],
["city"=>"Anakapalle","state"=>"Andhra Pradesh","id"=>"4"],
["city"=>"Anand","state"=>"Gujarat","id"=>"212"],
["city"=>"Anantapur","state"=>"Andhra Pradesh","id"=>"5"],
["city"=>"Anantnag","state"=>"Jammu and Kashmir","id"=>"324"],
["city"=>"Anjangaon","state"=>"Maharashtra","id"=>"580"],
["city"=>"Anjar","state"=>"Gujarat","id"=>"213"],
["city"=>"Ankleshwar","state"=>"Gujarat","id"=>"214"],
["city"=>"Arakkonam","state"=>"Tamil Nadu","id"=>"878"],
["city"=>"Arambagh","state"=>"West Bengal","id"=>"1175"],
["city"=>"Araria","state"=>"Bihar","id"=>"112"],
["city"=>"Arrah","state"=>"Bihar","id"=>"113"],
["city"=>"Arsikere","state"=>"Karnataka","id"=>"362"],
["city"=>"Aruppukkottai","state"=>"Tamil Nadu","id"=>"879"],
["city"=>"Arvi","state"=>"Maharashtra","id"=>"581"],
["city"=>"Arwal","state"=>"Bihar","id"=>"114"],
["city"=>"Asansol","state"=>"West Bengal","id"=>"1176"],
["city"=>"Asarganj","state"=>"Bihar","id"=>"115"],
["city"=>"Ashok Nagar","state"=>"Madhya Pradesh","id"=>"492"],
["city"=>"Athni","state"=>"Karnataka","id"=>"363"],
["city"=>"Attingal","state"=>"Kerala","id"=>"442"],
["city"=>"Aurangabad","state"=>"Maharashtra","id"=>"582"],
["city"=>"Azamgarh","state"=>"Uttar Pradesh","id"=>"1042"],
["city"=>"Bagaha","state"=>"Bihar","id"=>"117"],
["city"=>"Bageshwar","state"=>"Uttarakhand","id"=>"1155"],
["city"=>"Bahadurgarh","state"=>"Haryana","id"=>"281"],
["city"=>"Baharampur","state"=>"West Bengal","id"=>"1177"],
["city"=>"Bahraich","state"=>"Uttar Pradesh","id"=>"1043"],
["city"=>"Balaghat","state"=>"Madhya Pradesh","id"=>"493"],
["city"=>"Balangir","state"=>"Odisha","id"=>"711"],
["city"=>"Baleshwar Town","state"=>"Odisha","id"=>"712"],
["city"=>"Ballari","state"=>"Karnataka","id"=>"366"],
["city"=>"Balurghat","state"=>"West Bengal","id"=>"1178"],
["city"=>"Bankura","state"=>"West Bengal","id"=>"1179"],
["city"=>"Bapatla","state"=>"Andhra Pradesh","id"=>"6"],
["city"=>"Baramula","state"=>"Jammu and Kashmir","id"=>"325"],
["city"=>"Barbil","state"=>"Odisha","id"=>"713"],
["city"=>"Bargarh","state"=>"Odisha","id"=>"714"],
["city"=>"Barh","state"=>"Bihar","id"=>"118"],
["city"=>"Baripada Town","state"=>"Odisha","id"=>"715"],
["city"=>"Barnala","state"=>"Punjab","id"=>"750"],
["city"=>"Barpeta","state"=>"Assam","id"=>"87"],
["city"=>"Batala","state"=>"Punjab","id"=>"751"],
["city"=>"Bathinda","state"=>"Punjab","id"=>"752"],
["city"=>"Begusarai","state"=>"Bihar","id"=>"119"],
["city"=>"Belagavi","state"=>"Karnataka","id"=>"365"],
["city"=>"Bellampalle","state"=>"Telangana","id"=>"991"],
["city"=>"Belonia","state"=>"Tripura","id"=>"1031"],
["city"=>"Bengaluru","state"=>"Karnataka","id"=>"364"],
["city"=>"Bettiah","state"=>"Bihar","id"=>"120"],
["city"=>"Bhabua","state"=>"Bihar","id"=>"121"],
["city"=>"Bhadrachalam","state"=>"Telangana","id"=>"992"],
["city"=>"Bhadrak","state"=>"Odisha","id"=>"716"],
["city"=>"Bhagalpur","state"=>"Bihar","id"=>"122"],
["city"=>"Bhainsa","state"=>"Telangana","id"=>"993"],
["city"=>"Bharatpur","state"=>"Rajasthan","id"=>"806"],
["city"=>"Bharuch","state"=>"Gujarat","id"=>"215"],
["city"=>"Bhatapara","state"=>"Chhattisgarh","id"=>"184"],
["city"=>"Bhavnagar","state"=>"Gujarat","id"=>"216"],
["city"=>"Bhawanipatna","state"=>"Odisha","id"=>"717"],
["city"=>"Bheemunipatnam","state"=>"Andhra Pradesh","id"=>"7"],
["city"=>"Bhilai Nagar","state"=>"Chhattisgarh","id"=>"185"],
["city"=>"Bhilwara","state"=>"Rajasthan","id"=>"807"],
["city"=>"Bhimavaram","state"=>"Andhra Pradesh","id"=>"8"],
["city"=>"Bhiwandi","state"=>"Maharashtra","id"=>"583"],
["city"=>"Bhiwani","state"=>"Haryana","id"=>"282"],
["city"=>"Bhongir","state"=>"Telangana","id"=>"994"],
["city"=>"Bhopal","state"=>"Madhya Pradesh","id"=>"494"],
["city"=>"Bhubaneswar*","state"=>"Odisha","id"=>"718"],
["city"=>"Bhuj","state"=>"Gujarat","id"=>"217"],
["city"=>"Bikaner","state"=>"Rajasthan","id"=>"805"],
["city"=>"Bilaspur","state"=>"Chhattisgarh","id"=>"186"],
["city"=>"Bobbili","state"=>"Andhra Pradesh","id"=>"9"],
["city"=>"Bodhan","state"=>"Telangana","id"=>"995"],
["city"=>"Bokaro Steel City","state"=>"Jharkhand","id"=>"334"],
["city"=>"Bongaigaon City","state"=>"Assam","id"=>"88"],
["city"=>"Brahmapur","state"=>"Odisha","id"=>"719"],
["city"=>"Buxar","state"=>"Bihar","id"=>"123"],
["city"=>"Byasanagar","state"=>"Odisha","id"=>"720"],
["city"=>"Chaibasa","state"=>"Jharkhand","id"=>"335"],
["city"=>"Chalakudy","state"=>"Kerala","id"=>"443"],
["city"=>"Chandausi","state"=>"Uttar Pradesh","id"=>"1044"],
["city"=>"Chandigarh*","state"=>"Chandigarh","id"=>"182"],
["city"=>"Changanassery","state"=>"Kerala","id"=>"444"],
["city"=>"Charkhi Dadri","state"=>"Haryana","id"=>"283"],
["city"=>"Chatra","state"=>"Jharkhand","id"=>"336"],
["city"=>"Chennai*","state"=>"Tamil Nadu","id"=>"880"],
["city"=>"Cherthala","state"=>"Kerala","id"=>"445"],
["city"=>"Chhapra","state"=>"Gujarat","id"=>"218"],
["city"=>"Chikkamagaluru","state"=>"Karnataka","id"=>"367"],
["city"=>"Chilakaluripet","state"=>"Andhra Pradesh","id"=>"10"],
["city"=>"Chirala","state"=>"Andhra Pradesh","id"=>"11"],
["city"=>"Chirkunda","state"=>"Jharkhand","id"=>"337"],
["city"=>"Chirmiri","state"=>"Chhattisgarh","id"=>"187"],
["city"=>"Chittoor","state"=>"Andhra Pradesh","id"=>"12"],
["city"=>"Chittur-Thathamangalam","state"=>"Kerala","id"=>"446"],
["city"=>"Coimbatore","state"=>"Tamil Nadu","id"=>"881"],
["city"=>"Cuttack","state"=>"Odisha","id"=>"721"],
["city"=>"Dalli-Rajhara","state"=>"Chhattisgarh","id"=>"188"],
["city"=>"Darbhanga","state"=>"Bihar","id"=>"125"],
["city"=>"Darjiling","state"=>"West Bengal","id"=>"1180"],
["city"=>"Davanagere","state"=>"Karnataka","id"=>"368"],
["city"=>"Deesa","state"=>"Gujarat","id"=>"219"],
["city"=>"Dehradun","state"=>"Uttarakhand","id"=>"1156"],
["city"=>"Dehri-on-Sone","state"=>"Bihar","id"=>"126"],
["city"=>"Delhi","state"=>"Delhi","id"=>"203"],
["city"=>"Deoghar","state"=>"Jharkhand","id"=>"339"],
["city"=>"Dhamtari","state"=>"Chhattisgarh","id"=>"189"],
["city"=>"Dhanbad","state"=>"Jharkhand","id"=>"340"],
["city"=>"Dharmanagar","state"=>"Tripura","id"=>"1032"],
["city"=>"Dharmavaram","state"=>"Andhra Pradesh","id"=>"13"],
["city"=>"Dhenkanal","state"=>"Odisha","id"=>"722"],
["city"=>"Dhoraji","state"=>"Gujarat","id"=>"220"],
["city"=>"Dhubri","state"=>"Assam","id"=>"89"],
["city"=>"Dhule","state"=>"Maharashtra","id"=>"584"],
["city"=>"Dhuri","state"=>"Punjab","id"=>"753"],
["city"=>"Dibrugarh","state"=>"Assam","id"=>"90"],
["city"=>"Dimapur","state"=>"Nagaland","id"=>"705"],
["city"=>"Diphu","state"=>"Assam","id"=>"91"],
["city"=>"Dumka","state"=>"Jharkhand","id"=>"341"],
["city"=>"Dumraon","state"=>"Bihar","id"=>"127"],
["city"=>"Durg","state"=>"Chhattisgarh","id"=>"190"],
["city"=>"Eluru","state"=>"Andhra Pradesh","id"=>"14"],
["city"=>"English Bazar","state"=>"West Bengal","id"=>"1181"],
["city"=>"Erode","state"=>"Tamil Nadu","id"=>"882"],
["city"=>"Etawah","state"=>"Uttar Pradesh","id"=>"1045"],
["city"=>"Faridabad","state"=>"Haryana","id"=>"284"],
["city"=>"Faridkot","state"=>"Punjab","id"=>"754"],
["city"=>"Farooqnagar","state"=>"Telangana","id"=>"996"],
["city"=>"Fatehabad","state"=>"Haryana","id"=>"285"],
["city"=>"Fatehpur Sikri","state"=>"Uttar Pradesh","id"=>"1047"],
["city"=>"Fazilka","state"=>"Punjab","id"=>"755"],
["city"=>"Firozabad","state"=>"Uttar Pradesh","id"=>"1046"],
["city"=>"Firozpur","state"=>"Punjab","id"=>"756"],
["city"=>"Firozpur Cantt.","state"=>"Punjab","id"=>"757"],
["city"=>"Forbesganj","state"=>"Bihar","id"=>"128"],
["city"=>"Gadwal","state"=>"Telangana","id"=>"997"],
["city"=>"Gangarampur","state"=>"West Bengal","id"=>"1182"],
["city"=>"Ganjbasoda","state"=>"Madhya Pradesh","id"=>"495"],
["city"=>"Gaya","state"=>"Bihar","id"=>"129"],
["city"=>"Giridih","state"=>"Jharkhand","id"=>"342"],
["city"=>"Goalpara","state"=>"Assam","id"=>"92"],
["city"=>"Gobichettipalayam","state"=>"Tamil Nadu","id"=>"883"],
["city"=>"Gobindgarh","state"=>"Punjab","id"=>"758"],
["city"=>"Godhra","state"=>"Gujarat","id"=>"221"],
["city"=>"Gohana","state"=>"Haryana","id"=>"286"],
["city"=>"Gokak","state"=>"Karnataka","id"=>"369"],
["city"=>"Gooty","state"=>"Andhra Pradesh","id"=>"15"],
["city"=>"Gopalganj","state"=>"Bihar","id"=>"130"],
["city"=>"Greater Mumbai*","state"=>"Maharashtra","id"=>"607"],
["city"=>"Gudivada","state"=>"Andhra Pradesh","id"=>"16"],
["city"=>"Gudur","state"=>"Andhra Pradesh","id"=>"17"],
["city"=>"Gumia","state"=>"Jharkhand","id"=>"343"],
["city"=>"Guntakal","state"=>"Andhra Pradesh","id"=>"18"],
["city"=>"Guntur","state"=>"Andhra Pradesh","id"=>"19"],
["city"=>"Gurdaspur","state"=>"Punjab","id"=>"759"],
["city"=>"Gurgaon","state"=>"Haryana","id"=>"287"],
["city"=>"Guruvayoor","state"=>"Kerala","id"=>"447"],
["city"=>"Guwahati","state"=>"Assam","id"=>"93"],
["city"=>"Gwalior","state"=>"Madhya Pradesh","id"=>"496"],
["city"=>"Habra","state"=>"West Bengal","id"=>"1183"],
["city"=>"Hajipur","state"=>"Bihar","id"=>"131"],
["city"=>"Haldwani-cum-Kathgodam","state"=>"Uttarakhand","id"=>"1157"],
["city"=>"Hansi","state"=>"Haryana","id"=>"288"],
["city"=>"Hapur","state"=>"Uttar Pradesh","id"=>"1048"],
["city"=>"Hardoi *","state"=>"Uttar Pradesh","id"=>"1049"],
["city"=>"Hardwar","state"=>"Uttarakhand","id"=>"1158"],
["city"=>"Hazaribag","state"=>"Jharkhand","id"=>"344"],
["city"=>"Hindupur","state"=>"Andhra Pradesh","id"=>"20"],
["city"=>"Hisar","state"=>"Haryana","id"=>"289"],
["city"=>"Hoshiarpur","state"=>"Punjab","id"=>"760"],
["city"=>"Hubli-Dharwad","state"=>"Karnataka","id"=>"370"],
["city"=>"Hugli-Chinsurah","state"=>"West Bengal","id"=>"1184"],
["city"=>"Hyderabad*","state"=>"Telangana","id"=>"998"],
["city"=>"Ichalkaranji","state"=>"Maharashtra","id"=>"586"],
["city"=>"Imphal*","state"=>"Manipur","id"=>"695"],
["city"=>"Indore","state"=>"Madhya Pradesh","id"=>"497"],
["city"=>"Itarsi","state"=>"Madhya Pradesh","id"=>"498"],
["city"=>"Jabalpur","state"=>"Madhya Pradesh","id"=>"499"],
["city"=>"Jagdalpur","state"=>"Chhattisgarh","id"=>"191"],
["city"=>"Jaggaiahpet","state"=>"Andhra Pradesh","id"=>"21"],
["city"=>"Jagraon","state"=>"Punjab","id"=>"761"],
["city"=>"Jagtial","state"=>"Telangana","id"=>"999"],
["city"=>"Jaipur*","state"=>"Rajasthan","id"=>"808"],
["city"=>"Jalandhar","state"=>"Punjab","id"=>"763"],
["city"=>"Jalandhar Cantt.","state"=>"Punjab","id"=>"762"],
["city"=>"Jalpaiguri","state"=>"West Bengal","id"=>"1185"],
["city"=>"Jamalpur","state"=>"Bihar","id"=>"132"],
["city"=>"Jammalamadugu","state"=>"Andhra Pradesh","id"=>"22"],
["city"=>"Jammu","state"=>"Jammu and Kashmir","id"=>"326"],
["city"=>"Jamnagar","state"=>"Gujarat","id"=>"222"],
["city"=>"Jamshedpur","state"=>"Jharkhand","id"=>"345"],
["city"=>"Jamui","state"=>"Bihar","id"=>"133"],
["city"=>"Jangaon","state"=>"Telangana","id"=>"1000"],
["city"=>"Jatani","state"=>"Odisha","id"=>"723"],
["city"=>"Jehanabad","state"=>"Bihar","id"=>"134"],
["city"=>"Jhansi","state"=>"Uttar Pradesh","id"=>"1050"],
["city"=>"Jhargram","state"=>"West Bengal","id"=>"1186"],
["city"=>"Jharsuguda","state"=>"Odisha","id"=>"724"],
["city"=>"Jhumri Tilaiya","state"=>"Jharkhand","id"=>"346"],
["city"=>"Jind","state"=>"Haryana","id"=>"290"],
["city"=>"Jodhpur","state"=>"Rajasthan","id"=>"809"],
["city"=>"Jorhat","state"=>"Assam","id"=>"94"],
["city"=>"Kadapa","state"=>"Andhra Pradesh","id"=>"23"],
["city"=>"Kadi","state"=>"Gujarat","id"=>"223"],
["city"=>"Kadiri","state"=>"Andhra Pradesh","id"=>"24"],
["city"=>"Kagaznagar","state"=>"Telangana","id"=>"1001"],
["city"=>"Kailasahar","state"=>"Tripura","id"=>"1033"],
["city"=>"Kaithal","state"=>"Haryana","id"=>"291"],
["city"=>"Kakinada","state"=>"Andhra Pradesh","id"=>"25"],
["city"=>"Kalimpong","state"=>"West Bengal","id"=>"1187"],
["city"=>"Kalpi","state"=>"Uttar Pradesh","id"=>"1051"],
["city"=>"Kalyan-Dombivali","state"=>"Maharashtra","id"=>"587"],
["city"=>"Kamareddy","state"=>"Telangana","id"=>"1002"],
["city"=>"Kancheepuram","state"=>"Tamil Nadu","id"=>"884"],
["city"=>"Kandukur","state"=>"Andhra Pradesh","id"=>"26"],
["city"=>"Kanhangad","state"=>"Kerala","id"=>"448"],
["city"=>"Kannur","state"=>"Kerala","id"=>"449"],
["city"=>"Kanpur","state"=>"Uttar Pradesh","id"=>"1052"],
["city"=>"Kapadvanj","state"=>"Gujarat","id"=>"224"],
["city"=>"Kapurthala","state"=>"Punjab","id"=>"764"],
["city"=>"Karaikal","state"=>"Puducherry","id"=>"745"],
["city"=>"Karimganj","state"=>"Assam","id"=>"95"],
["city"=>"Karimnagar","state"=>"Telangana","id"=>"1003"],
["city"=>"Karjat","state"=>"Maharashtra","id"=>"588"],
["city"=>"Karnal","state"=>"Haryana","id"=>"292"],
["city"=>"Karur","state"=>"Tamil Nadu","id"=>"885"],
["city"=>"Karwar","state"=>"Karnataka","id"=>"371"],
["city"=>"Kasaragod","state"=>"Kerala","id"=>"450"],
["city"=>"Kashipur","state"=>"Uttarakhand","id"=>"1159"],
["city"=>"Kathua","state"=>"Jammu and Kashmir","id"=>"327"],
["city"=>"Katihar","state"=>"Bihar","id"=>"135"],
["city"=>"Kavali","state"=>"Andhra Pradesh","id"=>"27"],
["city"=>"Kayamkulam","state"=>"Kerala","id"=>"451"],
["city"=>"Kendrapara","state"=>"Odisha","id"=>"725"],
["city"=>"Kendujhar","state"=>"Odisha","id"=>"726"],
["city"=>"Keshod","state"=>"Gujarat","id"=>"225"],
["city"=>"Khair","state"=>"Uttar Pradesh","id"=>"1053"],
["city"=>"Khambhat","state"=>"Gujarat","id"=>"226"],
["city"=>"Khammam","state"=>"Telangana","id"=>"1004"],
["city"=>"Khanna","state"=>"Punjab","id"=>"765"],
["city"=>"Kharagpur","state"=>"West Bengal","id"=>"1188"],
["city"=>"Kharar","state"=>"Punjab","id"=>"766"],
["city"=>"Khowai","state"=>"Tripura","id"=>"1034"],
["city"=>"Kishanganj","state"=>"Bihar","id"=>"136"],
["city"=>"Kochi","state"=>"Kerala","id"=>"452"],
["city"=>"Kodungallur","state"=>"Kerala","id"=>"453"],
["city"=>"Kohima*","state"=>"Nagaland","id"=>"706"],
["city"=>"Kolar","state"=>"Karnataka","id"=>"372"],
["city"=>"Kolkata","state"=>"West Bengal","id"=>"1189"],
["city"=>"Kollam","state"=>"Kerala","id"=>"454"],
["city"=>"Koratla","state"=>"Telangana","id"=>"1005"],
["city"=>"Korba","state"=>"Chhattisgarh","id"=>"192"],
["city"=>"Kot Kapura","state"=>"Punjab","id"=>"767"],
["city"=>"Kothagudem","state"=>"Telangana","id"=>"1006"],
["city"=>"Kottayam","state"=>"Kerala","id"=>"455"],
["city"=>"Kovvur","state"=>"Andhra Pradesh","id"=>"28"],
["city"=>"Koyilandy","state"=>"Kerala","id"=>"480"],
["city"=>"Kozhikode","state"=>"Kerala","id"=>"456"],
["city"=>"Kunnamkulam","state"=>"Kerala","id"=>"457"],
["city"=>"Kurnool","state"=>"Andhra Pradesh","id"=>"29"],
["city"=>"Kyathampalle","state"=>"Telangana","id"=>"1007"],
["city"=>"Lachhmangarh","state"=>"Rajasthan","id"=>"810"],
["city"=>"Ladnu","state"=>"Rajasthan","id"=>"811"],
["city"=>"Ladwa","state"=>"Haryana","id"=>"293"],
["city"=>"Lahar","state"=>"Madhya Pradesh","id"=>"500"],
["city"=>"Laharpur","state"=>"Uttar Pradesh","id"=>"1054"],
["city"=>"Lakheri","state"=>"Rajasthan","id"=>"812"],
["city"=>"Lakhimpur","state"=>"Uttar Pradesh","id"=>"1055"],
["city"=>"Lakhisarai","state"=>"Bihar","id"=>"137"],
["city"=>"Lakshmeshwar","state"=>"Karnataka","id"=>"373"],
["city"=>"Lal Gopalganj Nindaura","state"=>"Uttar Pradesh","id"=>"1056"],
["city"=>"Lalganj","state"=>"Uttar Pradesh","id"=>"1058"],
["city"=>"Lalgudi","state"=>"Tamil Nadu","id"=>"886"],
["city"=>"Lalitpur","state"=>"Uttar Pradesh","id"=>"1057"],
["city"=>"Lalsot","state"=>"Rajasthan","id"=>"813"],
["city"=>"Lanka","state"=>"Assam","id"=>"96"],
["city"=>"Lar","state"=>"Uttar Pradesh","id"=>"1059"],
["city"=>"Lathi","state"=>"Gujarat","id"=>"227"],
["city"=>"Latur","state"=>"Maharashtra","id"=>"589"],
["city"=>"Lilong","state"=>"Manipur","id"=>"696"],
["city"=>"Limbdi","state"=>"Gujarat","id"=>"228"],
["city"=>"Lingsugur","state"=>"Karnataka","id"=>"374"],
["city"=>"Loha","state"=>"Maharashtra","id"=>"590"],
["city"=>"Lohardaga","state"=>"Jharkhand","id"=>"347"],
["city"=>"Lonar","state"=>"Maharashtra","id"=>"591"],
["city"=>"Lonavla","state"=>"Maharashtra","id"=>"592"],
["city"=>"Longowal","state"=>"Punjab","id"=>"768"],
["city"=>"Loni","state"=>"Uttar Pradesh","id"=>"1060"],
["city"=>"Losal","state"=>"Rajasthan","id"=>"814"],
["city"=>"Lucknow*","state"=>"Uttar Pradesh","id"=>"1061"],
["city"=>"Ludhiana","state"=>"Punjab","id"=>"769"],
["city"=>"Lumding","state"=>"Assam","id"=>"97"],
["city"=>"Lunawada","state"=>"Gujarat","id"=>"229"],
["city"=>"Lunglei","state"=>"Mizoram","id"=>"703"],
["city"=>"Macherla","state"=>"Andhra Pradesh","id"=>"30"],
["city"=>"Machilipatnam","state"=>"Andhra Pradesh","id"=>"31"],
["city"=>"Madanapalle","state"=>"Andhra Pradesh","id"=>"32"],
["city"=>"Maddur","state"=>"Karnataka","id"=>"375"],
["city"=>"Madhepura","state"=>"Bihar","id"=>"139"],
["city"=>"Madhubani","state"=>"Bihar","id"=>"140"],
["city"=>"Madhugiri","state"=>"Karnataka","id"=>"376"],
["city"=>"Madhupur","state"=>"Jharkhand","id"=>"348"],
["city"=>"Madikeri","state"=>"Karnataka","id"=>"377"],
["city"=>"Madurai","state"=>"Tamil Nadu","id"=>"887"],
["city"=>"Magadi","state"=>"Karnataka","id"=>"378"],
["city"=>"Mahad","state"=>"Maharashtra","id"=>"593"],
["city"=>"Mahalingapura","state"=>"Karnataka","id"=>"379"],
["city"=>"Maharajganj","state"=>"Bihar","id"=>"141"],
["city"=>"Maharajpur","state"=>"Madhya Pradesh","id"=>"501"],
["city"=>"Mahasamund","state"=>"Chhattisgarh","id"=>"193"],
["city"=>"Mahbubnagar","state"=>"Telangana","id"=>"1008"],
["city"=>"Mahe","state"=>"Puducherry","id"=>"746"],
["city"=>"Mahemdabad","state"=>"Gujarat","id"=>"236"],
["city"=>"Mahendragarh","state"=>"Haryana","id"=>"294"],
["city"=>"Mahesana","state"=>"Gujarat","id"=>"230"],
["city"=>"Mahidpur","state"=>"Madhya Pradesh","id"=>"502"],
["city"=>"Mahnar Bazar","state"=>"Bihar","id"=>"142"],
["city"=>"Mahuva","state"=>"Gujarat","id"=>"231"],
["city"=>"Maihar","state"=>"Madhya Pradesh","id"=>"503"],
["city"=>"Mainaguri","state"=>"West Bengal","id"=>"1190"],
["city"=>"Makhdumpur","state"=>"Bihar","id"=>"143"],
["city"=>"Makrana","state"=>"Rajasthan","id"=>"815"],
["city"=>"Malaj Khand","state"=>"Madhya Pradesh","id"=>"504"],
["city"=>"Malappuram","state"=>"Kerala","id"=>"458"],
["city"=>"Malavalli","state"=>"Karnataka","id"=>"380"],
["city"=>"Malda","state"=>"West Bengal","id"=>"1191"],
["city"=>"Malegaon","state"=>"Maharashtra","id"=>"594"],
["city"=>"Malerkotla","state"=>"Punjab","id"=>"770"],
["city"=>"Malkangiri","state"=>"Odisha","id"=>"727"],
["city"=>"Malkapur","state"=>"Maharashtra","id"=>"595"],
["city"=>"Malout","state"=>"Punjab","id"=>"771"],
["city"=>"Malpura","state"=>"Rajasthan","id"=>"816"],
["city"=>"Malur","state"=>"Karnataka","id"=>"381"],
["city"=>"Manachanallur","state"=>"Tamil Nadu","id"=>"888"],
["city"=>"Manasa","state"=>"Madhya Pradesh","id"=>"505"],
["city"=>"Manavadar","state"=>"Gujarat","id"=>"232"],
["city"=>"Manawar","state"=>"Madhya Pradesh","id"=>"506"],
["city"=>"Mancherial","state"=>"Telangana","id"=>"1009"],
["city"=>"Mandalgarh","state"=>"Rajasthan","id"=>"817"],
["city"=>"Mandamarri","state"=>"Telangana","id"=>"1010"],
["city"=>"Mandapeta","state"=>"Andhra Pradesh","id"=>"33"],
["city"=>"Mandawa","state"=>"Rajasthan","id"=>"818"],
["city"=>"Mandi","state"=>"Himachal Pradesh","id"=>"318"],
["city"=>"Mandi Dabwali","state"=>"Haryana","id"=>"295"],
["city"=>"Mandideep","state"=>"Madhya Pradesh","id"=>"507"],
["city"=>"Mandla","state"=>"Madhya Pradesh","id"=>"508"],
["city"=>"Mandsaur","state"=>"Madhya Pradesh","id"=>"509"],
["city"=>"Mandvi","state"=>"Gujarat","id"=>"233"],
["city"=>"Mandya","state"=>"Karnataka","id"=>"382"],
["city"=>"Manendragarh","state"=>"Chhattisgarh","id"=>"194"],
["city"=>"Maner","state"=>"Bihar","id"=>"144"],
["city"=>"Mangaldoi","state"=>"Assam","id"=>"98"],
["city"=>"Mangaluru","state"=>"Karnataka","id"=>"383"],
["city"=>"Mangalvedhe","state"=>"Maharashtra","id"=>"596"],
["city"=>"Manglaur","state"=>"Uttarakhand","id"=>"1160"],
["city"=>"Mangrol","state"=>"Rajasthan","id"=>"819"],
["city"=>"Mangrulpir","state"=>"Maharashtra","id"=>"597"],
["city"=>"Manihari","state"=>"Bihar","id"=>"145"],
["city"=>"Manjlegaon","state"=>"Maharashtra","id"=>"598"],
["city"=>"Mankachar","state"=>"Assam","id"=>"99"],
["city"=>"Manmad","state"=>"Maharashtra","id"=>"599"],
["city"=>"Mansa","state"=>"Punjab","id"=>"772"],
["city"=>"Manuguru","state"=>"Telangana","id"=>"1011"],
["city"=>"Manvi","state"=>"Karnataka","id"=>"384"],
["city"=>"Manwath","state"=>"Maharashtra","id"=>"600"],
["city"=>"Mapusa","state"=>"Goa","id"=>"205"],
["city"=>"Margao","state"=>"Goa","id"=>"206"],
["city"=>"Margherita","state"=>"Assam","id"=>"100"],
["city"=>"Marhaura","state"=>"Bihar","id"=>"146"],
["city"=>"Mariani","state"=>"Assam","id"=>"101"],
["city"=>"Marigaon","state"=>"Assam","id"=>"102"],
["city"=>"Markapur","state"=>"Andhra Pradesh","id"=>"34"],
["city"=>"Marmagao","state"=>"Goa","id"=>"207"],
["city"=>"Masaurhi","state"=>"Bihar","id"=>"147"],
["city"=>"Mathabhanga","state"=>"West Bengal","id"=>"1192"],
["city"=>"Mathura","state"=>"Uttar Pradesh","id"=>"1062"],
["city"=>"Mattannur","state"=>"Kerala","id"=>"459"],
["city"=>"Mauganj","state"=>"Madhya Pradesh","id"=>"510"],
["city"=>"Mavelikkara","state"=>"Kerala","id"=>"460"],
["city"=>"Mavoor","state"=>"Kerala","id"=>"461"],
["city"=>"Mayang Imphal","state"=>"Manipur","id"=>"697"],
["city"=>"Medak","state"=>"Telangana","id"=>"1012"],
["city"=>"Medininagar (Daltonganj)","state"=>"Jharkhand","id"=>"338"],
["city"=>"Medinipur","state"=>"West Bengal","id"=>"1193"],
["city"=>"Meerut","state"=>"Uttar Pradesh","id"=>"1063"],
["city"=>"Mehkar","state"=>"Maharashtra","id"=>"601"],
["city"=>"Memari","state"=>"West Bengal","id"=>"1194"],
["city"=>"Merta City","state"=>"Rajasthan","id"=>"820"],
["city"=>"Mhaswad","state"=>"Maharashtra","id"=>"602"],
["city"=>"Mhow Cantonment","state"=>"Madhya Pradesh","id"=>"511"],
["city"=>"Mhowgaon","state"=>"Madhya Pradesh","id"=>"512"],
["city"=>"Mihijam","state"=>"Jharkhand","id"=>"349"],
["city"=>"Mira-Bhayandar","state"=>"Maharashtra","id"=>"603"],
["city"=>"Mirganj","state"=>"Bihar","id"=>"148"],
["city"=>"Miryalaguda","state"=>"Telangana","id"=>"1013"],
["city"=>"Modasa","state"=>"Gujarat","id"=>"237"],
["city"=>"Modinagar","state"=>"Uttar Pradesh","id"=>"1064"],
["city"=>"Moga","state"=>"Punjab","id"=>"773"],
["city"=>"Mohali","state"=>"Punjab","id"=>"774"],
["city"=>"Mokameh","state"=>"Bihar","id"=>"149"],
["city"=>"Mokokchung","state"=>"Nagaland","id"=>"707"],
["city"=>"Monoharpur","state"=>"West Bengal","id"=>"1195"],
["city"=>"Moradabad","state"=>"Uttar Pradesh","id"=>"1065"],
["city"=>"Morena","state"=>"Madhya Pradesh","id"=>"513"],
["city"=>"Morinda, India","state"=>"Punjab","id"=>"775"],
["city"=>"Morshi","state"=>"Maharashtra","id"=>"604"],
["city"=>"Morvi","state"=>"Gujarat","id"=>"238"],
["city"=>"Motihari","state"=>"Bihar","id"=>"150"],
["city"=>"Motipur","state"=>"Bihar","id"=>"151"],
["city"=>"Mount Abu","state"=>"Rajasthan","id"=>"821"],
["city"=>"Mudabidri","state"=>"Karnataka","id"=>"386"],
["city"=>"Mudalagi","state"=>"Karnataka","id"=>"385"],
["city"=>"Muddebihal","state"=>"Karnataka","id"=>"387"],
["city"=>"Mudhol","state"=>"Karnataka","id"=>"388"],
["city"=>"Mukerian","state"=>"Punjab","id"=>"776"],
["city"=>"Mukhed","state"=>"Maharashtra","id"=>"605"],
["city"=>"Muktsar","state"=>"Punjab","id"=>"777"],
["city"=>"Mul","state"=>"Maharashtra","id"=>"606"],
["city"=>"Mulbagal","state"=>"Karnataka","id"=>"389"],
["city"=>"Multai","state"=>"Madhya Pradesh","id"=>"514"],
["city"=>"Mundargi","state"=>"Karnataka","id"=>"390"],
["city"=>"Mundi","state"=>"Madhya Pradesh","id"=>"515"],
["city"=>"Mungeli","state"=>"Chhattisgarh","id"=>"195"],
["city"=>"Munger","state"=>"Bihar","id"=>"152"],
["city"=>"Murliganj","state"=>"Bihar","id"=>"153"],
["city"=>"Murshidabad","state"=>"West Bengal","id"=>"1196"],
["city"=>"Murtijapur","state"=>"Maharashtra","id"=>"608"],
["city"=>"Murwara (Katni)","state"=>"Madhya Pradesh","id"=>"516"],
["city"=>"Musabani","state"=>"Jharkhand","id"=>"350"],
["city"=>"Mussoorie","state"=>"Uttarakhand","id"=>"1161"],
["city"=>"Muvattupuzha","state"=>"Kerala","id"=>"462"],
["city"=>"Muzaffarpur","state"=>"Bihar","id"=>"154"],
["city"=>"Mysore","state"=>"Karnatka","id"=>"439"],
["city"=>"Nabadwip","state"=>"West Bengal","id"=>"1197"],
["city"=>"Nabarangapur","state"=>"Odisha","id"=>"728"],
["city"=>"Nabha","state"=>"Punjab","id"=>"778"],
["city"=>"Nadbai","state"=>"Rajasthan","id"=>"822"],
["city"=>"Nadiad","state"=>"Gujarat","id"=>"239"],
["city"=>"Nagaon","state"=>"Assam","id"=>"103"],
["city"=>"Nagapattinam","state"=>"Tamil Nadu","id"=>"889"],
["city"=>"Nagar","state"=>"Rajasthan","id"=>"823"],
["city"=>"Nagari","state"=>"Andhra Pradesh","id"=>"35"],
["city"=>"Nagarkurnool","state"=>"Telangana","id"=>"1014"],
["city"=>"Nagaur","state"=>"Rajasthan","id"=>"824"],
["city"=>"Nagda","state"=>"Madhya Pradesh","id"=>"517"],
["city"=>"Nagercoil","state"=>"Tamil Nadu","id"=>"890"],
["city"=>"Nagina","state"=>"Uttar Pradesh","id"=>"1066"],
["city"=>"Nagla","state"=>"Uttarakhand","id"=>"1162"],
["city"=>"Nagpur","state"=>"Maharashtra","id"=>"609"],
["city"=>"Nahan","state"=>"Himachal Pradesh","id"=>"319"],
["city"=>"Naharlagun","state"=>"Arunachal Pradesh","id"=>"85"],
["city"=>"Naidupet","state"=>"Andhra Pradesh","id"=>"36"],
["city"=>"Naihati","state"=>"West Bengal","id"=>"1198"],
["city"=>"Naila Janjgir","state"=>"Chhattisgarh","id"=>"196"],
["city"=>"Nainital","state"=>"Uttarakhand","id"=>"1163"],
["city"=>"Nainpur","state"=>"Madhya Pradesh","id"=>"518"],
["city"=>"Najibabad","state"=>"Uttar Pradesh","id"=>"1067"],
["city"=>"Nakodar","state"=>"Punjab","id"=>"779"],
["city"=>"Nakur","state"=>"Uttar Pradesh","id"=>"1068"],
["city"=>"Nalbari","state"=>"Assam","id"=>"104"],
["city"=>"Namagiripettai","state"=>"Tamil Nadu","id"=>"891"],
["city"=>"Namakkal","state"=>"Tamil Nadu","id"=>"892"],
["city"=>"Nanded-Waghala","state"=>"Maharashtra","id"=>"610"],
["city"=>"Nandgaon","state"=>"Maharashtra","id"=>"611"],
["city"=>"Nandivaram-Guduvancheri","state"=>"Tamil Nadu","id"=>"893"],
["city"=>"Nandura","state"=>"Maharashtra","id"=>"612"],
["city"=>"Nandurbar","state"=>"Maharashtra","id"=>"613"],
["city"=>"Nandyal","state"=>"Andhra Pradesh","id"=>"37"],
["city"=>"Nangal","state"=>"Punjab","id"=>"780"],
["city"=>"Nanjangud","state"=>"Karnataka","id"=>"391"],
["city"=>"Nanjikottai","state"=>"Tamil Nadu","id"=>"894"],
["city"=>"Nanpara","state"=>"Uttar Pradesh","id"=>"1069"],
["city"=>"Narasapuram","state"=>"Andhra Pradesh","id"=>"38"],
["city"=>"Narasaraopet","state"=>"Andhra Pradesh","id"=>"39"],
["city"=>"Naraura","state"=>"Uttar Pradesh","id"=>"1070"],
["city"=>"Narayanpet","state"=>"Telangana","id"=>"1015"],
["city"=>"Nargund","state"=>"Karnataka","id"=>"392"],
["city"=>"Narkatiaganj","state"=>"Bihar","id"=>"155"],
["city"=>"Narkhed","state"=>"Maharashtra","id"=>"614"],
["city"=>"Narnaul","state"=>"Haryana","id"=>"296"],
["city"=>"Narsinghgarh","state"=>"Madhya Pradesh","id"=>"520"],
["city"=>"Narsipatnam","state"=>"Andhra Pradesh","id"=>"40"],
["city"=>"Narwana","state"=>"Haryana","id"=>"297"],
["city"=>"Nashik","state"=>"Maharashtra","id"=>"615"],
["city"=>"Nasirabad","state"=>"Rajasthan","id"=>"825"],
["city"=>"Natham","state"=>"Tamil Nadu","id"=>"895"],
["city"=>"Nathdwara","state"=>"Rajasthan","id"=>"826"],
["city"=>"Naugachhia","state"=>"Bihar","id"=>"156"],
["city"=>"Naugawan Sadat","state"=>"Uttar Pradesh","id"=>"1071"],
["city"=>"Nautanwa","state"=>"Uttar Pradesh","id"=>"1072"],
["city"=>"Navalgund","state"=>"Karnataka","id"=>"393"],
["city"=>"Navi Mumbai","state"=>"Maharashtra","id"=>"616"],
["city"=>"Navsari","state"=>"Gujarat","id"=>"240"],
["city"=>"Nawabganj","state"=>"Uttar Pradesh","id"=>"1073"],
["city"=>"Nawada","state"=>"Bihar","id"=>"157"],
["city"=>"Nawanshahr","state"=>"Punjab","id"=>"781"],
["city"=>"Nawapur","state"=>"Maharashtra","id"=>"617"],
["city"=>"Nedumangad","state"=>"Kerala","id"=>"463"],
["city"=>"Neem-Ka-Thana","state"=>"Rajasthan","id"=>"827"],
["city"=>"Neemuch","state"=>"Madhya Pradesh","id"=>"521"],
["city"=>"Nehtaur","state"=>"Uttar Pradesh","id"=>"1074"],
["city"=>"Nelamangala","state"=>"Karnataka","id"=>"394"],
["city"=>"Nellikuppam","state"=>"Tamil Nadu","id"=>"896"],
["city"=>"Nellore","state"=>"Andhra Pradesh","id"=>"41"],
["city"=>"Nepanagar","state"=>"Madhya Pradesh","id"=>"522"],
["city"=>"New Delhi*","state"=>"Delhi","id"=>"204"],
["city"=>"Neyveli (TS)","state"=>"Tamil Nadu","id"=>"897"],
["city"=>"Neyyattinkara","state"=>"Kerala","id"=>"464"],
["city"=>"Nidadavole","state"=>"Andhra Pradesh","id"=>"42"],
["city"=>"Nilambur","state"=>"Kerala","id"=>"465"],
["city"=>"Nilanga","state"=>"Maharashtra","id"=>"618"],
["city"=>"Nimbahera","state"=>"Rajasthan","id"=>"828"],
["city"=>"Nirmal","state"=>"Telangana","id"=>"1016"],
["city"=>"Niwai","state"=>"Uttar Pradesh","id"=>"1075"],
["city"=>"Niwari","state"=>"Madhya Pradesh","id"=>"523"],
["city"=>"Nizamabad","state"=>"Telangana","id"=>"1017"],
["city"=>"Nohar","state"=>"Rajasthan","id"=>"829"],
["city"=>"Noida","state"=>"Uttar Pradesh","id"=>"1076"],
["city"=>"Nokha","state"=>"Rajasthan","id"=>"830"],
["city"=>"Nongstoin","state"=>"Meghalaya","id"=>"699"],
["city"=>"Noorpur","state"=>"Uttar Pradesh","id"=>"1077"],
["city"=>"North Lakhimpur","state"=>"Assam","id"=>"105"],
["city"=>"Nowgong","state"=>"Madhya Pradesh","id"=>"524"],
["city"=>"Nowrozabad (Khodargama)","state"=>"Madhya Pradesh","id"=>"525"],
["city"=>"Nuzvid","state"=>"Andhra Pradesh","id"=>"43"],
["city"=>"O' Valley","state"=>"Tamil Nadu","id"=>"898"],
["city"=>"Obra","state"=>"Uttar Pradesh","id"=>"1078"],
["city"=>"Oddanchatram","state"=>"Tamil Nadu","id"=>"899"],
["city"=>"Ongole","state"=>"Andhra Pradesh","id"=>"44"],
["city"=>"Orai","state"=>"Uttar Pradesh","id"=>"1079"],
["city"=>"Osmanabad","state"=>"Maharashtra","id"=>"619"],
["city"=>"Ottappalam","state"=>"Kerala","id"=>"466"],
["city"=>"Ozar","state"=>"Maharashtra","id"=>"620"],
["city"=>"P.N.Patti","state"=>"Tamil Nadu","id"=>"900"],
["city"=>"Pachora","state"=>"Maharashtra","id"=>"621"],
["city"=>"Pachore","state"=>"Madhya Pradesh","id"=>"526"],
["city"=>"Pacode","state"=>"Tamil Nadu","id"=>"901"],
["city"=>"Padmanabhapuram","state"=>"Tamil Nadu","id"=>"902"],
["city"=>"Padra","state"=>"Gujarat","id"=>"241"],
["city"=>"Padrauna","state"=>"Uttar Pradesh","id"=>"1080"],
["city"=>"Paithan","state"=>"Maharashtra","id"=>"622"],
["city"=>"Pakaur","state"=>"Jharkhand","id"=>"351"],
["city"=>"Palacole","state"=>"Andhra Pradesh","id"=>"45"],
["city"=>"Palai","state"=>"Kerala","id"=>"467"],
["city"=>"Palakkad","state"=>"Kerala","id"=>"468"],
["city"=>"Palampur","state"=>"Himachal Pradesh","id"=>"320"],
["city"=>"Palani","state"=>"Tamil Nadu","id"=>"903"],
["city"=>"Palanpur","state"=>"Gujarat","id"=>"242"],
["city"=>"Palasa Kasibugga","state"=>"Andhra Pradesh","id"=>"46"],
["city"=>"Palghar","state"=>"Maharashtra","id"=>"623"],
["city"=>"Pali","state"=>"Rajasthan","id"=>"831"],
["city"=>"Palia Kalan","state"=>"Uttar Pradesh","id"=>"1081"],
["city"=>"Palitana","state"=>"Gujarat","id"=>"243"],
["city"=>"Palladam","state"=>"Tamil Nadu","id"=>"904"],
["city"=>"Pallapatti","state"=>"Tamil Nadu","id"=>"905"],
["city"=>"Pallikonda","state"=>"Tamil Nadu","id"=>"906"],
["city"=>"Palwal","state"=>"Haryana","id"=>"298"],
["city"=>"Palwancha","state"=>"Telangana","id"=>"1018"],
["city"=>"Panagar","state"=>"Madhya Pradesh","id"=>"528"],
["city"=>"Panagudi","state"=>"Tamil Nadu","id"=>"907"],
["city"=>"Panaji*","state"=>"Goa","id"=>"208"],
["city"=>"Panamattom","state"=>"Kerala","id"=>"469"],
["city"=>"Panchkula","state"=>"Haryana","id"=>"299"],
["city"=>"Panchla","state"=>"West Bengal","id"=>"1199"],
["city"=>"Pandharkaoda","state"=>"Maharashtra","id"=>"624"],
["city"=>"Pandharpur","state"=>"Maharashtra","id"=>"625"],
["city"=>"Pandhurna","state"=>"Madhya Pradesh","id"=>"529"],
["city"=>"Pandua","state"=>"West Bengal","id"=>"1200"],
["city"=>"Panipat","state"=>"Haryana","id"=>"300"],
["city"=>"Panna","state"=>"Madhya Pradesh","id"=>"530"],
["city"=>"Panniyannur","state"=>"Kerala","id"=>"470"],
["city"=>"Panruti","state"=>"Tamil Nadu","id"=>"908"],
["city"=>"Panvel","state"=>"Maharashtra","id"=>"626"],
["city"=>"Pappinisseri","state"=>"Kerala","id"=>"471"],
["city"=>"Paradip","state"=>"Odisha","id"=>"729"],
["city"=>"Paramakudi","state"=>"Tamil Nadu","id"=>"909"],
["city"=>"Parangipettai","state"=>"Tamil Nadu","id"=>"910"],
["city"=>"Parasi","state"=>"Uttar Pradesh","id"=>"1082"],
["city"=>"Paravoor","state"=>"Kerala","id"=>"472"],
["city"=>"Parbhani","state"=>"Maharashtra","id"=>"627"],
["city"=>"Pardi","state"=>"Gujarat","id"=>"244"],
["city"=>"Parlakhemundi","state"=>"Odisha","id"=>"730"],
["city"=>"Parli","state"=>"Maharashtra","id"=>"628"],
["city"=>"Partur","state"=>"Maharashtra","id"=>"629"],
["city"=>"Parvathipuram","state"=>"Andhra Pradesh","id"=>"47"],
["city"=>"Pasan","state"=>"Madhya Pradesh","id"=>"531"],
["city"=>"Paschim Punropara","state"=>"West Bengal","id"=>"1201"],
["city"=>"Pasighat","state"=>"Arunachal Pradesh","id"=>"86"],
["city"=>"Patan","state"=>"Gujarat","id"=>"245"],
["city"=>"Pathanamthitta","state"=>"Kerala","id"=>"473"],
["city"=>"Pathankot","state"=>"Punjab","id"=>"782"],
["city"=>"Pathardi","state"=>"Maharashtra","id"=>"630"],
["city"=>"Pathri","state"=>"Maharashtra","id"=>"631"],
["city"=>"Patiala","state"=>"Punjab","id"=>"783"],
["city"=>"Patna*","state"=>"Bihar","id"=>"159"],
["city"=>"Patratu","state"=>"Jharkhand","id"=>"352"],
["city"=>"Pattamundai","state"=>"Odisha","id"=>"731"],
["city"=>"Patti","state"=>"Punjab","id"=>"785"],
["city"=>"Pattran","state"=>"Punjab","id"=>"784"],
["city"=>"Pattukkottai","state"=>"Tamil Nadu","id"=>"911"],
["city"=>"Patur","state"=>"Maharashtra","id"=>"632"],
["city"=>"Pauni","state"=>"Maharashtra","id"=>"633"],
["city"=>"Pauri","state"=>"Uttarakhand","id"=>"1164"],
["city"=>"Pavagada","state"=>"Karnataka","id"=>"395"],
["city"=>"Pedana","state"=>"Andhra Pradesh","id"=>"48"],
["city"=>"Peddapuram","state"=>"Andhra Pradesh","id"=>"49"],
["city"=>"Pehowa","state"=>"Haryana","id"=>"301"],
["city"=>"Pen","state"=>"Maharashtra","id"=>"634"],
["city"=>"Perambalur","state"=>"Tamil Nadu","id"=>"912"],
["city"=>"Peravurani","state"=>"Tamil Nadu","id"=>"913"],
["city"=>"Peringathur","state"=>"Kerala","id"=>"474"],
["city"=>"Perinthalmanna","state"=>"Kerala","id"=>"475"],
["city"=>"Periyakulam","state"=>"Tamil Nadu","id"=>"914"],
["city"=>"Periyasemur","state"=>"Tamil Nadu","id"=>"915"],
["city"=>"Pernampattu","state"=>"Tamil Nadu","id"=>"916"],
["city"=>"Perumbavoor","state"=>"Kerala","id"=>"476"],
["city"=>"Petlad","state"=>"Gujarat","id"=>"246"],
["city"=>"Phagwara","state"=>"Punjab","id"=>"786"],
["city"=>"Phalodi","state"=>"Rajasthan","id"=>"832"],
["city"=>"Phaltan","state"=>"Maharashtra","id"=>"635"],
["city"=>"Phillaur","state"=>"Punjab","id"=>"787"],
["city"=>"Phulabani","state"=>"Odisha","id"=>"732"],
["city"=>"Phulera","state"=>"Rajasthan","id"=>"833"],
["city"=>"Phulpur","state"=>"Uttar Pradesh","id"=>"1083"],
["city"=>"Phusro","state"=>"Jharkhand","id"=>"353"],
["city"=>"Pihani","state"=>"Uttar Pradesh","id"=>"1084"],
["city"=>"Pilani","state"=>"Rajasthan","id"=>"834"],
["city"=>"Pilibanga","state"=>"Rajasthan","id"=>"835"],
["city"=>"Pilibhit","state"=>"Uttar Pradesh","id"=>"1085"],
["city"=>"Pilkhuwa","state"=>"Uttar Pradesh","id"=>"1086"],
["city"=>"Pindwara","state"=>"Rajasthan","id"=>"836"],
["city"=>"Pinjore","state"=>"Haryana","id"=>"302"],
["city"=>"Pipar City","state"=>"Rajasthan","id"=>"837"],
["city"=>"Pipariya","state"=>"Madhya Pradesh","id"=>"532"],
["city"=>"Piriyapatna","state"=>"Karnataka","id"=>"396"],
["city"=>"Piro","state"=>"Bihar","id"=>"160"],
["city"=>"Pithampur","state"=>"Madhya Pradesh","id"=>"533"],
["city"=>"Pithapuram","state"=>"Andhra Pradesh","id"=>"50"],
["city"=>"Pithoragarh","state"=>"Uttarakhand","id"=>"1165"],
["city"=>"Pollachi","state"=>"Tamil Nadu","id"=>"917"],
["city"=>"Polur","state"=>"Tamil Nadu","id"=>"918"],
["city"=>"Pondicherry*","state"=>"Puducherry","id"=>"747"],
["city"=>"Ponnani","state"=>"Kerala","id"=>"477"],
["city"=>"Ponneri","state"=>"Tamil Nadu","id"=>"919"],
["city"=>"Ponnur","state"=>"Andhra Pradesh","id"=>"51"],
["city"=>"Porbandar","state"=>"Gujarat","id"=>"247"],
["city"=>"Porsa","state"=>"Madhya Pradesh","id"=>"534"],
["city"=>"Port Blair*","state"=>"Andaman and Nicobar Islands","id"=>"1"],
["city"=>"Powayan","state"=>"Uttar Pradesh","id"=>"1087"],
["city"=>"Prantij","state"=>"Rajasthan","id"=>"838"],
["city"=>"Pratapgarh","state"=>"Tripura","id"=>"1035"],
["city"=>"Prithvipur","state"=>"Madhya Pradesh","id"=>"535"],
["city"=>"Proddatur","state"=>"Andhra Pradesh","id"=>"52"],
["city"=>"Pudukkottai","state"=>"Tamil Nadu","id"=>"920"],
["city"=>"Pudupattinam","state"=>"Tamil Nadu","id"=>"921"],
["city"=>"Pukhrayan","state"=>"Uttar Pradesh","id"=>"1088"],
["city"=>"Pulgaon","state"=>"Maharashtra","id"=>"636"],
["city"=>"Puliyankudi","state"=>"Tamil Nadu","id"=>"922"],
["city"=>"Punalur","state"=>"Kerala","id"=>"478"],
["city"=>"Punch","state"=>"Jammu and Kashmir","id"=>"328"],
["city"=>"Pune","state"=>"Maharashtra","id"=>"637"],
["city"=>"Punganur","state"=>"Andhra Pradesh","id"=>"53"],
["city"=>"Punjaipugalur","state"=>"Tamil Nadu","id"=>"923"],
["city"=>"Puranpur","state"=>"Uttar Pradesh","id"=>"1089"],
["city"=>"Puri","state"=>"Odisha","id"=>"733"],
["city"=>"Purna","state"=>"Maharashtra","id"=>"638"],
["city"=>"Purnia","state"=>"Bihar","id"=>"161"],
["city"=>"Purquazi","state"=>"Uttar Pradesh","id"=>"1090"],
["city"=>"Purulia","state"=>"West Bengal","id"=>"1202"],
["city"=>"Purwa","state"=>"Uttar Pradesh","id"=>"1091"],
["city"=>"Pusad","state"=>"Maharashtra","id"=>"639"],
["city"=>"Puthuppally","state"=>"Kerala","id"=>"479"],
["city"=>"Puttur","state"=>"Karnataka","id"=>"397"],
["city"=>"Qadian","state"=>"Punjab","id"=>"788"],
["city"=>"Raayachuru","state"=>"Karnataka","id"=>"399"],
["city"=>"Rabkavi Banhatti","state"=>"Karnataka","id"=>"398"],
["city"=>"Radhanpur","state"=>"Gujarat","id"=>"248"],
["city"=>"Rae Bareli","state"=>"Uttar Pradesh","id"=>"1092"],
["city"=>"Rafiganj","state"=>"Bihar","id"=>"162"],
["city"=>"Raghogarh-Vijaypur","state"=>"Madhya Pradesh","id"=>"536"],
["city"=>"Raghunathganj","state"=>"West Bengal","id"=>"1204"],
["city"=>"Raghunathpur","state"=>"West Bengal","id"=>"1203"],
["city"=>"Rahatgarh","state"=>"Madhya Pradesh","id"=>"537"],
["city"=>"Rahuri","state"=>"Maharashtra","id"=>"640"],
["city"=>"Raiganj","state"=>"West Bengal","id"=>"1205"],
["city"=>"Raigarh","state"=>"Chhattisgarh","id"=>"197"],
["city"=>"Raikot","state"=>"Punjab","id"=>"789"],
["city"=>"Raipur*","state"=>"Chhattisgarh","id"=>"198"],
["city"=>"Rairangpur","state"=>"Odisha","id"=>"734"],
["city"=>"Raisen","state"=>"Madhya Pradesh","id"=>"538"],
["city"=>"Raisinghnagar","state"=>"Rajasthan","id"=>"840"],
["city"=>"Rajagangapur","state"=>"Odisha","id"=>"735"],
["city"=>"Rajahmundry","state"=>"Andhra Pradesh","id"=>"55"],
["city"=>"Rajakhera","state"=>"Rajasthan","id"=>"841"],
["city"=>"Rajaldesar","state"=>"Rajasthan","id"=>"842"],
["city"=>"Rajam","state"=>"Andhra Pradesh","id"=>"56"],
["city"=>"Rajampet","state"=>"Andhra Pradesh","id"=>"57"],
["city"=>"Rajapalayam","state"=>"Tamil Nadu","id"=>"925"],
["city"=>"Rajauri","state"=>"Jammu and Kashmir","id"=>"329"],
["city"=>"Rajgarh","state"=>"Madhya Pradesh","id"=>"539"],
["city"=>"Rajgarh (Alwar)","state"=>"Rajasthan","id"=>"843"],
["city"=>"Rajgarh (Churu)","state"=>"Rajasthan","id"=>"844"],
["city"=>"Rajgir","state"=>"Bihar","id"=>"163"],
["city"=>"Rajkot","state"=>"Gujarat","id"=>"249"],
["city"=>"Rajnandgaon","state"=>"Chhattisgarh","id"=>"199"],
["city"=>"Rajpipla","state"=>"Gujarat","id"=>"250"],
["city"=>"Rajpura","state"=>"Punjab","id"=>"790"],
["city"=>"Rajsamand","state"=>"Rajasthan","id"=>"845"],
["city"=>"Rajula","state"=>"Gujarat","id"=>"251"],
["city"=>"Rajura","state"=>"Maharashtra","id"=>"641"],
["city"=>"Ramachandrapuram","state"=>"Andhra Pradesh","id"=>"58"],
["city"=>"Ramagundam","state"=>"Telangana","id"=>"1019"],
["city"=>"Ramanagaram","state"=>"Karnataka","id"=>"401"],
["city"=>"Ramanathapuram","state"=>"Tamil Nadu","id"=>"926"],
["city"=>"Ramdurg","state"=>"Karnataka","id"=>"402"],
["city"=>"Rameshwaram","state"=>"Tamil Nadu","id"=>"927"],
["city"=>"Ramganj Mandi","state"=>"Rajasthan","id"=>"846"],
["city"=>"Ramgarh","state"=>"Jharkhand","id"=>"354"],
["city"=>"Ramnagar","state"=>"Uttarakhand","id"=>"1166"],
["city"=>"Ramngarh","state"=>"Rajasthan","id"=>"847"],
["city"=>"Rampur","state"=>"Uttar Pradesh","id"=>"1093"],
["city"=>"Rampur Maniharan","state"=>"Uttar Pradesh","id"=>"1095"],
["city"=>"Rampura Phul","state"=>"Punjab","id"=>"791"],
["city"=>"Rampurhat","state"=>"West Bengal","id"=>"1206"],
["city"=>"Ramtek","state"=>"Maharashtra","id"=>"642"],
["city"=>"Ranaghat","state"=>"West Bengal","id"=>"1207"],
["city"=>"Ranavav","state"=>"Gujarat","id"=>"252"],
["city"=>"Ranchi*","state"=>"Jharkhand","id"=>"355"],
["city"=>"Ranebennuru","state"=>"Karnataka","id"=>"400"],
["city"=>"Rangia","state"=>"Assam","id"=>"106"],
["city"=>"Rania","state"=>"Haryana","id"=>"303"],
["city"=>"Ranibennur","state"=>"Karnataka","id"=>"403"],
["city"=>"Ranipet","state"=>"Tamil Nadu","id"=>"924"],
["city"=>"Rapar","state"=>"Gujarat","id"=>"253"],
["city"=>"Rasipuram","state"=>"Tamil Nadu","id"=>"928"],
["city"=>"Rasra","state"=>"Uttar Pradesh","id"=>"1096"],
["city"=>"Ratangarh","state"=>"Rajasthan","id"=>"848"],
["city"=>"Rath","state"=>"Uttar Pradesh","id"=>"1097"],
["city"=>"Ratia","state"=>"Haryana","id"=>"304"],
["city"=>"Ratlam","state"=>"Madhya Pradesh","id"=>"540"],
["city"=>"Ratnagiri","state"=>"Maharashtra","id"=>"643"],
["city"=>"Rau","state"=>"Madhya Pradesh","id"=>"541"],
["city"=>"Raurkela","state"=>"Odisha","id"=>"736"],
["city"=>"Raver","state"=>"Maharashtra","id"=>"644"],
["city"=>"Rawatbhata","state"=>"Rajasthan","id"=>"849"],
["city"=>"Rawatsar","state"=>"Rajasthan","id"=>"850"],
["city"=>"Raxaul Bazar","state"=>"Bihar","id"=>"165"],
["city"=>"Rayachoti","state"=>"Andhra Pradesh","id"=>"59"],
["city"=>"Rayadurg","state"=>"Andhra Pradesh","id"=>"60"],
["city"=>"Rayagada","state"=>"Odisha","id"=>"737"],
["city"=>"Reengus","state"=>"Rajasthan","id"=>"851"],
["city"=>"Rehli","state"=>"Madhya Pradesh","id"=>"542"],
["city"=>"Renigunta","state"=>"Andhra Pradesh","id"=>"61"],
["city"=>"Renukoot","state"=>"Uttar Pradesh","id"=>"1098"],
["city"=>"Reoti","state"=>"Uttar Pradesh","id"=>"1099"],
["city"=>"Repalle","state"=>"Andhra Pradesh","id"=>"62"],
["city"=>"Revelganj","state"=>"Bihar","id"=>"166"],
["city"=>"Rewa","state"=>"Madhya Pradesh","id"=>"543"],
["city"=>"Rewari","state"=>"Haryana","id"=>"305"],
["city"=>"Rishikesh","state"=>"Uttarakhand","id"=>"1167"],
["city"=>"Risod","state"=>"Maharashtra","id"=>"645"],
["city"=>"Robertsganj","state"=>"Uttar Pradesh","id"=>"1100"],
["city"=>"Robertson Pet","state"=>"Karnataka","id"=>"404"],
["city"=>"Rohtak","state"=>"Haryana","id"=>"306"],
["city"=>"Ron","state"=>"Karnataka","id"=>"405"],
["city"=>"Roorkee","state"=>"Uttarakhand","id"=>"1168"],
["city"=>"Rosera","state"=>"Bihar","id"=>"167"],
["city"=>"Rudauli","state"=>"Uttar Pradesh","id"=>"1101"],
["city"=>"Rudrapur","state"=>"Uttarakhand","id"=>"1169"],
["city"=>"Rupnagar","state"=>"Punjab","id"=>"792"],
["city"=>"Sabalgarh","state"=>"Madhya Pradesh","id"=>"544"],
["city"=>"Sadabad","state"=>"Uttar Pradesh","id"=>"1103"],
["city"=>"Sadalagi","state"=>"Karnataka","id"=>"406"],
["city"=>"Sadasivpet","state"=>"Telangana","id"=>"1020"],
["city"=>"Sadri","state"=>"Rajasthan","id"=>"852"],
["city"=>"Sadulpur","state"=>"Rajasthan","id"=>"854"],
["city"=>"Sadulshahar","state"=>"Rajasthan","id"=>"853"],
["city"=>"Safidon","state"=>"Haryana","id"=>"307"],
["city"=>"Safipur","state"=>"Uttar Pradesh","id"=>"1104"],
["city"=>"Sagar","state"=>"Madhya Pradesh","id"=>"545"],
["city"=>"Sagara","state"=>"Karnataka","id"=>"407"],
["city"=>"Sagwara","state"=>"Rajasthan","id"=>"855"],
["city"=>"Saharanpur","state"=>"Uttar Pradesh","id"=>"1105"],
["city"=>"Saharsa","state"=>"Bihar","id"=>"168"],
["city"=>"Sahaspur","state"=>"Uttar Pradesh","id"=>"1106"],
["city"=>"Sahaswan","state"=>"Uttar Pradesh","id"=>"1107"],
["city"=>"Sahawar","state"=>"Uttar Pradesh","id"=>"1108"],
["city"=>"Sahibganj","state"=>"Jharkhand","id"=>"356"],
["city"=>"Sahjanwa","state"=>"Uttar Pradesh","id"=>"1109"],
["city"=>"Saidpur","state"=>"Uttar Pradesh","id"=>"1110"],
["city"=>"Saiha","state"=>"Mizoram","id"=>"704"],
["city"=>"Sailu","state"=>"Maharashtra","id"=>"646"],
["city"=>"Sainthia","state"=>"West Bengal","id"=>"1208"],
["city"=>"Sakaleshapura","state"=>"Karnataka","id"=>"408"],
["city"=>"Sakti","state"=>"Chhattisgarh","id"=>"200"],
["city"=>"Salaya","state"=>"Gujarat","id"=>"254"],
["city"=>"Salem","state"=>"Tamil Nadu","id"=>"929"],
["city"=>"Salur","state"=>"Andhra Pradesh","id"=>"63"],
["city"=>"Samalkha","state"=>"Haryana","id"=>"308"],
["city"=>"Samalkot","state"=>"Andhra Pradesh","id"=>"64"],
["city"=>"Samana","state"=>"Punjab","id"=>"793"],
["city"=>"Samastipur","state"=>"Bihar","id"=>"169"],
["city"=>"Sambalpur","state"=>"Odisha","id"=>"738"],
["city"=>"Sambhal","state"=>"Uttar Pradesh","id"=>"1111"],
["city"=>"Sambhar","state"=>"Rajasthan","id"=>"856"],
["city"=>"Samdhan","state"=>"Uttar Pradesh","id"=>"1112"],
["city"=>"Samthar","state"=>"Uttar Pradesh","id"=>"1113"],
["city"=>"Sanand","state"=>"Gujarat","id"=>"255"],
["city"=>"Sanawad","state"=>"Madhya Pradesh","id"=>"546"],
["city"=>"Sanchore","state"=>"Rajasthan","id"=>"857"],
["city"=>"Sandi","state"=>"Uttar Pradesh","id"=>"1114"],
["city"=>"Sandila","state"=>"Uttar Pradesh","id"=>"1115"],
["city"=>"Sanduru","state"=>"Karnataka","id"=>"410"],
["city"=>"Sangamner","state"=>"Maharashtra","id"=>"647"],
["city"=>"Sangareddy","state"=>"Telangana","id"=>"1021"],
["city"=>"Sangaria","state"=>"Rajasthan","id"=>"858"],
["city"=>"Sangli","state"=>"Maharashtra","id"=>"648"],
["city"=>"Sangole","state"=>"Maharashtra","id"=>"649"],
["city"=>"Sangrur","state"=>"Punjab","id"=>"794"],
["city"=>"Sankarankoil","state"=>"Tamil Nadu","id"=>"930"],
["city"=>"Sankari","state"=>"Tamil Nadu","id"=>"931"],
["city"=>"Sankeshwara","state"=>"Karnataka","id"=>"411"],
["city"=>"Santipur","state"=>"West Bengal","id"=>"1209"],
["city"=>"Sarangpur","state"=>"Madhya Pradesh","id"=>"547"],
["city"=>"Sardarshahar","state"=>"Rajasthan","id"=>"859"],
["city"=>"Sardhana","state"=>"Uttar Pradesh","id"=>"1116"],
["city"=>"Sarni","state"=>"Madhya Pradesh","id"=>"548"],
["city"=>"Sarsod","state"=>"Haryana","id"=>"309"],
["city"=>"Sasaram","state"=>"Bihar","id"=>"170"],
["city"=>"Sasvad","state"=>"Maharashtra","id"=>"650"],
["city"=>"Satana","state"=>"Maharashtra","id"=>"651"],
["city"=>"Satara","state"=>"Maharashtra","id"=>"652"],
["city"=>"Sathyamangalam","state"=>"Tamil Nadu","id"=>"932"],
["city"=>"Satna","state"=>"Madhya Pradesh","id"=>"549"],
["city"=>"Sattenapalle","state"=>"Andhra Pradesh","id"=>"65"],
["city"=>"Sattur","state"=>"Tamil Nadu","id"=>"933"],
["city"=>"Saunda","state"=>"Jharkhand","id"=>"357"],
["city"=>"Saundatti-Yellamma","state"=>"Karnataka","id"=>"412"],
["city"=>"Sausar","state"=>"Madhya Pradesh","id"=>"550"],
["city"=>"Savanur","state"=>"Karnataka","id"=>"413"],
["city"=>"Savarkundla","state"=>"Gujarat","id"=>"256"],
["city"=>"Savner","state"=>"Maharashtra","id"=>"653"],
["city"=>"Sawai Madhopur","state"=>"Rajasthan","id"=>"860"],
["city"=>"Sawantwadi","state"=>"Maharashtra","id"=>"654"],
["city"=>"Sedam","state"=>"Karnataka","id"=>"414"],
["city"=>"Sehore","state"=>"Madhya Pradesh","id"=>"551"],
["city"=>"Sendhwa","state"=>"Madhya Pradesh","id"=>"552"],
["city"=>"Seohara","state"=>"Uttar Pradesh","id"=>"1117"],
["city"=>"Seoni","state"=>"Madhya Pradesh","id"=>"553"],
["city"=>"Seoni-Malwa","state"=>"Madhya Pradesh","id"=>"554"],
["city"=>"Shahabad","state"=>"Karnataka","id"=>"415"],
["city"=>"Shahabad, Hardoi","state"=>"Uttar Pradesh","id"=>"1118"],
["city"=>"Shahabad, Rampur","state"=>"Uttar Pradesh","id"=>"1119"],
["city"=>"Shahade","state"=>"Maharashtra","id"=>"655"],
["city"=>"Shahbad","state"=>"Haryana","id"=>"310"],
["city"=>"Shahdol","state"=>"Madhya Pradesh","id"=>"555"],
["city"=>"Shahganj","state"=>"Uttar Pradesh","id"=>"1120"],
["city"=>"Shahjahanpur","state"=>"Uttar Pradesh","id"=>"1121"],
["city"=>"Shahpur","state"=>"Karnataka","id"=>"416"],
["city"=>"Shahpura","state"=>"Rajasthan","id"=>"862"],
["city"=>"Shajapur","state"=>"Madhya Pradesh","id"=>"556"],
["city"=>"Shamgarh","state"=>"Madhya Pradesh","id"=>"557"],
["city"=>"Shamli","state"=>"Uttar Pradesh","id"=>"1122"],
["city"=>"Shamsabad, Agra","state"=>"Uttar Pradesh","id"=>"1123"],
["city"=>"Shamsabad, Farrukhabad","state"=>"Uttar Pradesh","id"=>"1124"],
["city"=>"Shegaon","state"=>"Maharashtra","id"=>"656"],
["city"=>"Sheikhpura","state"=>"Bihar","id"=>"171"],
["city"=>"Shendurjana","state"=>"Maharashtra","id"=>"657"],
["city"=>"Shenkottai","state"=>"Tamil Nadu","id"=>"934"],
["city"=>"Sheoganj","state"=>"Rajasthan","id"=>"863"],
["city"=>"Sheohar","state"=>"Bihar","id"=>"172"],
["city"=>"Sheopur","state"=>"Madhya Pradesh","id"=>"558"],
["city"=>"Sherghati","state"=>"Bihar","id"=>"173"],
["city"=>"Sherkot","state"=>"Uttar Pradesh","id"=>"1125"],
["city"=>"Shiggaon","state"=>"Karnataka","id"=>"417"],
["city"=>"Shikaripur","state"=>"Karnataka","id"=>"418"],
["city"=>"Shikarpur, Bulandshahr","state"=>"Uttar Pradesh","id"=>"1126"],
["city"=>"Shikohabad","state"=>"Uttar Pradesh","id"=>"1127"],
["city"=>"Shillong*","state"=>"Meghalaya","id"=>"700"],
["city"=>"Shimla*","state"=>"Himachal Pradesh","id"=>"321"],
["city"=>"Shirdi","state"=>"Maharashtra","id"=>"658"],
["city"=>"Shirpur-Warwade","state"=>"Maharashtra","id"=>"659"],
["city"=>"Shirur","state"=>"Maharashtra","id"=>"660"],
["city"=>"Shishgarh","state"=>"Uttar Pradesh","id"=>"1128"],
["city"=>"Shivamogga","state"=>"Karnataka","id"=>"419"],
["city"=>"Shivpuri","state"=>"Madhya Pradesh","id"=>"559"],
["city"=>"Sholavandan","state"=>"Tamil Nadu","id"=>"935"],
["city"=>"Sholingur","state"=>"Tamil Nadu","id"=>"936"],
["city"=>"Shoranur","state"=>"Kerala","id"=>"481"],
["city"=>"Shrigonda","state"=>"Maharashtra","id"=>"661"],
["city"=>"Shrirampur","state"=>"Maharashtra","id"=>"662"],
["city"=>"Shrirangapattana","state"=>"Karnataka","id"=>"421"],
["city"=>"Shujalpur","state"=>"Madhya Pradesh","id"=>"560"],
["city"=>"Siana","state"=>"Uttar Pradesh","id"=>"1129"],
["city"=>"Sibsagar","state"=>"Assam","id"=>"107"],
["city"=>"Siddipet","state"=>"Telangana","id"=>"1022"],
["city"=>"Sidhi","state"=>"Madhya Pradesh","id"=>"561"],
["city"=>"Sidhpur","state"=>"Gujarat","id"=>"257"],
["city"=>"Sidlaghatta","state"=>"Karnataka","id"=>"422"],
["city"=>"Sihor","state"=>"Gujarat","id"=>"258"],
["city"=>"Sihora","state"=>"Madhya Pradesh","id"=>"562"],
["city"=>"Sikanderpur","state"=>"Uttar Pradesh","id"=>"1130"],
["city"=>"Sikandra Rao","state"=>"Uttar Pradesh","id"=>"1131"],
["city"=>"Sikandrabad","state"=>"Uttar Pradesh","id"=>"1132"],
["city"=>"Sikar","state"=>"Rajasthan","id"=>"864"],
["city"=>"Silao","state"=>"Bihar","id"=>"174"],
["city"=>"Silapathar","state"=>"Assam","id"=>"108"],
["city"=>"Silchar","state"=>"Assam","id"=>"109"],
["city"=>"Siliguri","state"=>"West Bengal","id"=>"1210"],
["city"=>"Sillod","state"=>"Maharashtra","id"=>"663"],
["city"=>"Silvassa*","state"=>"Dadra and Nagar Haveli","id"=>"202"],
["city"=>"Simdega","state"=>"Jharkhand","id"=>"358"],
["city"=>"Sindagi","state"=>"Karnataka","id"=>"409"],
["city"=>"Sindhagi","state"=>"Karnataka","id"=>"423"],
["city"=>"Sindhnur","state"=>"Karnataka","id"=>"424"],
["city"=>"Singrauli","state"=>"Madhya Pradesh","id"=>"563"],
["city"=>"Sinnar","state"=>"Maharashtra","id"=>"664"],
["city"=>"Sira","state"=>"Karnataka","id"=>"425"],
["city"=>"Sircilla","state"=>"Telangana","id"=>"1023"],
["city"=>"Sirhind Fatehgarh Sahib","state"=>"Punjab","id"=>"795"],
["city"=>"Sirkali","state"=>"Tamil Nadu","id"=>"937"],
["city"=>"Sirohi","state"=>"Rajasthan","id"=>"865"],
["city"=>"Sironj","state"=>"Madhya Pradesh","id"=>"564"],
["city"=>"Sirsa","state"=>"Haryana","id"=>"311"],
["city"=>"Sirsaganj","state"=>"Uttar Pradesh","id"=>"1133"],
["city"=>"Sirsi","state"=>"Uttar Pradesh","id"=>"1134"],
["city"=>"Siruguppa","state"=>"Karnataka","id"=>"427"],
["city"=>"Sitamarhi","state"=>"Bihar","id"=>"175"],
["city"=>"Sitapur","state"=>"Uttar Pradesh","id"=>"1135"],
["city"=>"Sitarganj","state"=>"Uttarakhand","id"=>"1170"],
["city"=>"Sivaganga","state"=>"Tamil Nadu","id"=>"938"],
["city"=>"Sivagiri","state"=>"Tamil Nadu","id"=>"939"],
["city"=>"Sivakasi","state"=>"Tamil Nadu","id"=>"940"],
["city"=>"Siwan","state"=>"Bihar","id"=>"176"],
["city"=>"Sohagpur","state"=>"Madhya Pradesh","id"=>"565"],
["city"=>"Sohna","state"=>"Haryana","id"=>"312"],
["city"=>"Sojat","state"=>"Rajasthan","id"=>"866"],
["city"=>"Solan","state"=>"Himachal Pradesh","id"=>"322"],
["city"=>"Solapur","state"=>"Maharashtra","id"=>"665"],
["city"=>"Sonamukhi","state"=>"West Bengal","id"=>"1211"],
["city"=>"Sonepur","state"=>"Bihar","id"=>"177"],
["city"=>"Songadh","state"=>"Gujarat","id"=>"259"],
["city"=>"Sonipat","state"=>"Haryana","id"=>"313"],
["city"=>"Sopore","state"=>"Jammu and Kashmir","id"=>"330"],
["city"=>"Soro","state"=>"Odisha","id"=>"739"],
["city"=>"Soron","state"=>"Uttar Pradesh","id"=>"1136"],
["city"=>"Soyagaon","state"=>"Maharashtra","id"=>"666"],
["city"=>"Sri Madhopur","state"=>"Rajasthan","id"=>"867"],
["city"=>"Srikakulam","state"=>"Andhra Pradesh","id"=>"66"],
["city"=>"Srikalahasti","state"=>"Andhra Pradesh","id"=>"67"],
["city"=>"Srinagar","state"=>"Uttarakhand","id"=>"1171"],
["city"=>"Srinagar*","state"=>"Jammu and Kashmir","id"=>"331"],
["city"=>"Srinivaspur","state"=>"Karnataka","id"=>"428"],
["city"=>"Srirampore","state"=>"West Bengal","id"=>"1212"],
["city"=>"Srisailam Project (Right Flank Colony) Township","state"=>"Andhra Pradesh","id"=>"68"],
["city"=>"Srivilliputhur","state"=>"Tamil Nadu","id"=>"941"],
["city"=>"Suar","state"=>"Uttar Pradesh","id"=>"1137"],
["city"=>"Sugauli","state"=>"Bihar","id"=>"178"],
["city"=>"Sujangarh","state"=>"Rajasthan","id"=>"868"],
["city"=>"Sujanpur","state"=>"Punjab","id"=>"796"],
["city"=>"Sullurpeta","state"=>"Andhra Pradesh","id"=>"69"],
["city"=>"Sultanganj","state"=>"Bihar","id"=>"179"],
["city"=>"Sultanpur","state"=>"Uttar Pradesh","id"=>"1138"],
["city"=>"Sumerpur","state"=>"Uttar Pradesh","id"=>"1139"],
["city"=>"Sunabeda","state"=>"Odisha","id"=>"740"],
["city"=>"Sunam","state"=>"Punjab","id"=>"797"],
["city"=>"Sundargarh","state"=>"Odisha","id"=>"741"],
["city"=>"Sundarnagar","state"=>"Himachal Pradesh","id"=>"323"],
["city"=>"Supaul","state"=>"Bihar","id"=>"180"],
["city"=>"Surandai","state"=>"Tamil Nadu","id"=>"942"],
["city"=>"Surapura","state"=>"Karnataka","id"=>"420"],
["city"=>"Surat","state"=>"Gujarat","id"=>"260"],
["city"=>"Suratgarh","state"=>"Rajasthan","id"=>"870"],
["city"=>"Suri","state"=>"West Bengal","id"=>"1213"],
["city"=>"Suriyampalayam","state"=>"Tamil Nadu","id"=>"943"],
["city"=>"Suryapet","state"=>"Telangana","id"=>"1024"],
["city"=>"Tadepalligudem","state"=>"Andhra Pradesh","id"=>"70"],
["city"=>"Tadpatri","state"=>"Andhra Pradesh","id"=>"71"],
["city"=>"Taki","state"=>"West Bengal","id"=>"1214"],
["city"=>"Talaja","state"=>"Gujarat","id"=>"261"],
["city"=>"Talcher","state"=>"Odisha","id"=>"742"],
["city"=>"Talegaon Dabhade","state"=>"Maharashtra","id"=>"667"],
["city"=>"Talikota","state"=>"Karnataka","id"=>"432"],
["city"=>"Taliparamba","state"=>"Kerala","id"=>"482"],
["city"=>"Talode","state"=>"Maharashtra","id"=>"668"],
["city"=>"Talwara","state"=>"Punjab","id"=>"798"],
["city"=>"Tamluk","state"=>"West Bengal","id"=>"1215"],
["city"=>"Tanda","state"=>"Uttar Pradesh","id"=>"1140"],
["city"=>"Tandur","state"=>"Telangana","id"=>"1025"],
["city"=>"Tanuku","state"=>"Andhra Pradesh","id"=>"72"],
["city"=>"Tarakeswar","state"=>"West Bengal","id"=>"1216"],
["city"=>"Tarana","state"=>"Madhya Pradesh","id"=>"566"],
["city"=>"Taranagar","state"=>"Rajasthan","id"=>"871"],
["city"=>"Taraori","state"=>"Haryana","id"=>"314"],
["city"=>"Tarbha","state"=>"Odisha","id"=>"743"],
["city"=>"Tarikere","state"=>"Karnataka","id"=>"429"],
["city"=>"Tarn Taran","state"=>"Punjab","id"=>"799"],
["city"=>"Tasgaon","state"=>"Maharashtra","id"=>"669"],
["city"=>"Tehri","state"=>"Uttarakhand","id"=>"1172"],
["city"=>"Tekkalakote","state"=>"Karnataka","id"=>"430"],
["city"=>"Tenali","state"=>"Andhra Pradesh","id"=>"73"],
["city"=>"Tenkasi","state"=>"Tamil Nadu","id"=>"944"],
["city"=>"Tenu dam-cum-Kathhara","state"=>"Jharkhand","id"=>"359"],
["city"=>"Terdal","state"=>"Karnataka","id"=>"431"],
["city"=>"Tezpur","state"=>"Assam","id"=>"110"],
["city"=>"Thakurdwara","state"=>"Uttar Pradesh","id"=>"1141"],
["city"=>"Thammampatti","state"=>"Tamil Nadu","id"=>"945"],
["city"=>"Thana Bhawan","state"=>"Uttar Pradesh","id"=>"1142"],
["city"=>"Thane","state"=>"Maharashtra","id"=>"670"],
["city"=>"Thanesar","state"=>"Haryana","id"=>"315"],
["city"=>"Thangadh","state"=>"Gujarat","id"=>"262"],
["city"=>"Thanjavur","state"=>"Tamil Nadu","id"=>"946"],
["city"=>"Tharad","state"=>"Gujarat","id"=>"263"],
["city"=>"Tharamangalam","state"=>"Tamil Nadu","id"=>"947"],
["city"=>"Tharangambadi","state"=>"Tamil Nadu","id"=>"948"],
["city"=>"Theni Allinagaram","state"=>"Tamil Nadu","id"=>"949"],
["city"=>"Thirumangalam","state"=>"Tamil Nadu","id"=>"950"],
["city"=>"Thirupuvanam","state"=>"Tamil Nadu","id"=>"951"],
["city"=>"Thiruthuraipoondi","state"=>"Tamil Nadu","id"=>"952"],
["city"=>"Thiruvalla","state"=>"Kerala","id"=>"483"],
["city"=>"Thiruvallur","state"=>"Tamil Nadu","id"=>"953"],
["city"=>"Thiruvananthapuram","state"=>"Kerala","id"=>"484"],
["city"=>"Thiruvarur","state"=>"Tamil Nadu","id"=>"954"],
["city"=>"Thodupuzha","state"=>"Kerala","id"=>"485"],
["city"=>"Thoubal","state"=>"Manipur","id"=>"698"],
["city"=>"Thrissur","state"=>"Kerala","id"=>"486"],
["city"=>"Thuraiyur","state"=>"Tamil Nadu","id"=>"955"],
["city"=>"Tikamgarh","state"=>"Madhya Pradesh","id"=>"567"],
["city"=>"Tilda Newra","state"=>"Chhattisgarh","id"=>"201"],
["city"=>"Tilhar","state"=>"Uttar Pradesh","id"=>"1143"],
["city"=>"Tindivanam","state"=>"Tamil Nadu","id"=>"956"],
["city"=>"Tinsukia","state"=>"Assam","id"=>"111"],
["city"=>"Tiptur","state"=>"Karnataka","id"=>"433"],
["city"=>"Tirora","state"=>"Maharashtra","id"=>"671"],
["city"=>"Tiruchendur","state"=>"Tamil Nadu","id"=>"957"],
["city"=>"Tiruchengode","state"=>"Tamil Nadu","id"=>"958"],
["city"=>"Tiruchirappalli","state"=>"Tamil Nadu","id"=>"959"],
["city"=>"Tirukalukundram","state"=>"Tamil Nadu","id"=>"960"],
["city"=>"Tirukkoyilur","state"=>"Tamil Nadu","id"=>"961"],
["city"=>"Tirunelveli","state"=>"Tamil Nadu","id"=>"962"],
["city"=>"Tirupathur","state"=>"Tamil Nadu","id"=>"964"],
["city"=>"Tirupati","state"=>"Andhra Pradesh","id"=>"74"],
["city"=>"Tiruppur","state"=>"Tamil Nadu","id"=>"965"],
["city"=>"Tirur","state"=>"Kerala","id"=>"487"],
["city"=>"Tiruttani","state"=>"Tamil Nadu","id"=>"966"],
["city"=>"Tiruvannamalai","state"=>"Tamil Nadu","id"=>"967"],
["city"=>"Tiruvethipuram","state"=>"Tamil Nadu","id"=>"968"],
["city"=>"Tiruvuru","state"=>"Andhra Pradesh","id"=>"75"],
["city"=>"Tirwaganj","state"=>"Uttar Pradesh","id"=>"1144"],
["city"=>"Titlagarh","state"=>"Odisha","id"=>"744"],
["city"=>"Tittakudi","state"=>"Tamil Nadu","id"=>"969"],
["city"=>"Todabhim","state"=>"Rajasthan","id"=>"872"],
["city"=>"Todaraisingh","state"=>"Rajasthan","id"=>"873"],
["city"=>"Tohana","state"=>"Haryana","id"=>"316"],
["city"=>"Tonk","state"=>"Rajasthan","id"=>"874"],
["city"=>"Tuensang","state"=>"Nagaland","id"=>"708"],
["city"=>"Tuljapur","state"=>"Maharashtra","id"=>"672"],
["city"=>"Tulsipur","state"=>"Uttar Pradesh","id"=>"1145"],
["city"=>"Tumkur","state"=>"Karnataka","id"=>"434"],
["city"=>"Tumsar","state"=>"Maharashtra","id"=>"673"],
["city"=>"Tundla","state"=>"Uttar Pradesh","id"=>"1146"],
["city"=>"Tuni","state"=>"Andhra Pradesh","id"=>"76"],
["city"=>"Tura","state"=>"Meghalaya","id"=>"701"],
["city"=>"Uchgaon","state"=>"Maharashtra","id"=>"674"],
["city"=>"Udaipur","state"=>"Tripura","id"=>"1036"],
["city"=>"Udaipurwati","state"=>"Rajasthan","id"=>"876"],
["city"=>"Udgir","state"=>"Maharashtra","id"=>"675"],
["city"=>"Udhagamandalam","state"=>"Tamil Nadu","id"=>"970"],
["city"=>"Udhampur","state"=>"Jammu and Kashmir","id"=>"332"],
["city"=>"Udumalaipettai","state"=>"Tamil Nadu","id"=>"971"],
["city"=>"Udupi","state"=>"Karnataka","id"=>"435"],
["city"=>"Ujhani","state"=>"Uttar Pradesh","id"=>"1147"],
["city"=>"Ujjain","state"=>"Madhya Pradesh","id"=>"568"],
["city"=>"Umarga","state"=>"Maharashtra","id"=>"676"],
["city"=>"Umaria","state"=>"Madhya Pradesh","id"=>"569"],
["city"=>"Umarkhed","state"=>"Maharashtra","id"=>"677"],
["city"=>"Umbergaon","state"=>"Gujarat","id"=>"264"],
["city"=>"Umred","state"=>"Maharashtra","id"=>"678"],
["city"=>"Umreth","state"=>"Gujarat","id"=>"265"],
["city"=>"Una","state"=>"Gujarat","id"=>"266"],
["city"=>"Unjha","state"=>"Gujarat","id"=>"267"],
["city"=>"Unnamalaikadai","state"=>"Tamil Nadu","id"=>"972"],
["city"=>"Unnao","state"=>"Uttar Pradesh","id"=>"1148"],
["city"=>"Upleta","state"=>"Gujarat","id"=>"268"],
["city"=>"Uran","state"=>"Maharashtra","id"=>"679"],
["city"=>"Uran Islampur","state"=>"Maharashtra","id"=>"680"],
["city"=>"Uravakonda","state"=>"Andhra Pradesh","id"=>"77"],
["city"=>"Urmar Tanda","state"=>"Punjab","id"=>"800"],
["city"=>"Usilampatti","state"=>"Tamil Nadu","id"=>"973"],
["city"=>"Uthamapalayam","state"=>"Tamil Nadu","id"=>"974"],
["city"=>"Uthiramerur","state"=>"Tamil Nadu","id"=>"975"],
["city"=>"Utraula","state"=>"Uttar Pradesh","id"=>"1149"],
["city"=>"Vadakkuvalliyur","state"=>"Tamil Nadu","id"=>"976"],
["city"=>"Vadalur","state"=>"Tamil Nadu","id"=>"977"],
["city"=>"Vadgaon Kasba","state"=>"Maharashtra","id"=>"681"],
["city"=>"Vadipatti","state"=>"Tamil Nadu","id"=>"978"],
["city"=>"Vadnagar","state"=>"Gujarat","id"=>"269"],
["city"=>"Vadodara","state"=>"Gujarat","id"=>"270"],
["city"=>"Vaijapur","state"=>"Maharashtra","id"=>"682"],
["city"=>"Vaikom","state"=>"Kerala","id"=>"488"],
["city"=>"Valparai","state"=>"Tamil Nadu","id"=>"979"],
["city"=>"Valsad","state"=>"Gujarat","id"=>"271"],
["city"=>"Vandavasi","state"=>"Tamil Nadu","id"=>"980"],
["city"=>"Vaniyambadi","state"=>"Tamil Nadu","id"=>"981"],
["city"=>"Vapi","state"=>"Gujarat","id"=>"273"],
["city"=>"Varanasi","state"=>"Uttar Pradesh","id"=>"1150"],
["city"=>"Varkala","state"=>"Kerala","id"=>"489"],
["city"=>"Vasai-Virar","state"=>"Maharashtra","id"=>"683"],
["city"=>"Vatakara","state"=>"Kerala","id"=>"490"],
["city"=>"Vedaranyam","state"=>"Tamil Nadu","id"=>"982"],
["city"=>"Vellakoil","state"=>"Tamil Nadu","id"=>"983"],
["city"=>"Vellore","state"=>"Tamil Nadu","id"=>"984"],
["city"=>"Venkatagiri","state"=>"Andhra Pradesh","id"=>"78"],
["city"=>"Veraval","state"=>"Gujarat","id"=>"274"],
["city"=>"Vidisha","state"=>"Madhya Pradesh","id"=>"570"],
["city"=>"Vijainagar, Ajmer","state"=>"Rajasthan","id"=>"877"],
["city"=>"Vijapur","state"=>"Gujarat","id"=>"275"],
["city"=>"Vijayapura","state"=>"Karnataka","id"=>"436"],
["city"=>"Vijayawada","state"=>"Andhra Pradesh","id"=>"79"],
["city"=>"Vijaypur","state"=>"Madhya Pradesh","id"=>"571"],
["city"=>"Vikarabad","state"=>"Telangana","id"=>"1026"],
["city"=>"Vikramasingapuram","state"=>"Tamil Nadu","id"=>"985"],
["city"=>"Viluppuram","state"=>"Tamil Nadu","id"=>"986"],
["city"=>"Vinukonda","state"=>"Andhra Pradesh","id"=>"80"],
["city"=>"Viramgam","state"=>"Gujarat","id"=>"276"],
["city"=>"Virudhachalam","state"=>"Tamil Nadu","id"=>"987"],
["city"=>"Virudhunagar","state"=>"Tamil Nadu","id"=>"988"],
["city"=>"Visakhapatnam","state"=>"Andhra Pradesh","id"=>"81"],
["city"=>"Visnagar","state"=>"Gujarat","id"=>"277"],
["city"=>"Viswanatham","state"=>"Tamil Nadu","id"=>"989"],
["city"=>"Vita","state"=>"Maharashtra","id"=>"684"],
["city"=>"Vizianagaram","state"=>"Andhra Pradesh","id"=>"82"],
["city"=>"Vrindavan","state"=>"Uttar Pradesh","id"=>"1151"],
["city"=>"Vyara","state"=>"Gujarat","id"=>"278"],
["city"=>"Wadgaon Road","state"=>"Maharashtra","id"=>"685"],
["city"=>"Wadhwan","state"=>"Gujarat","id"=>"279"],
["city"=>"Wadi","state"=>"Karnataka","id"=>"437"],
["city"=>"Wai","state"=>"Maharashtra","id"=>"686"],
["city"=>"Wanaparthy","state"=>"Telangana","id"=>"1027"],
["city"=>"Wani","state"=>"Maharashtra","id"=>"687"],
["city"=>"Wankaner","state"=>"Gujarat","id"=>"280"],
["city"=>"Wara Seoni","state"=>"Madhya Pradesh","id"=>"572"],
["city"=>"Warangal","state"=>"Telangana","id"=>"1028"],
["city"=>"Wardha","state"=>"Maharashtra","id"=>"688"],
["city"=>"Warhapur","state"=>"Uttar Pradesh","id"=>"1152"],
["city"=>"Warisaliganj","state"=>"Bihar","id"=>"181"],
["city"=>"Warora","state"=>"Maharashtra","id"=>"689"],
["city"=>"Warud","state"=>"Maharashtra","id"=>"690"],
["city"=>"Washim","state"=>"Maharashtra","id"=>"691"],
["city"=>"Wokha","state"=>"Nagaland","id"=>"709"],
["city"=>"Yadgir","state"=>"Karnataka","id"=>"438"],
["city"=>"Yamunanagar","state"=>"Haryana","id"=>"317"],
["city"=>"Yanam","state"=>"Puducherry","id"=>"748"],
["city"=>"Yavatmal","state"=>"Maharashtra","id"=>"692"],
["city"=>"Yawal","state"=>"Maharashtra","id"=>"693"],
["city"=>"Yellandu","state"=>"Telangana","id"=>"1029"],
["city"=>"Yemmiganur","state"=>"Andhra Pradesh","id"=>"83"],
["city"=>"Yerraguntla","state"=>"Andhra Pradesh","id"=>"84"],
["city"=>"Yevla","state"=>"Maharashtra","id"=>"694"],
["city"=>"Zaidpur","state"=>"Uttar Pradesh","id"=>"1153"],
["city"=>"Zamania","state"=>"Uttar Pradesh","id"=>"1154"],
["city"=>"Zira","state"=>"Punjab","id"=>"801"],
["city"=>"Zirakpur","state"=>"Punjab","id"=>"802"],
["city"=>"Zunheboto","state"=>"Nagaland","id"=>"710"],
];
?>